### ISSUE TITLE
StackOverflow exception when serializing

### ISSUE THREAD

**Issue by lcy2008a** [RuedigerMoeller/fast-serialization#104]
Hi,

We have used a LruCache object we defined and met StackOverflow exception when serialize it. Here is the code:

``` java
    public class LruCache<K, V> implements Serializable {
        private static final long serialVersionUID = -2016748957655976688L;
        private static final float hashTableLoadFactor = 0.75f;

        private final LinkedHashMap<K, V> delegate;
        private final int cacheSize;

        public LruCache(int cacheSize) {
            if (cacheSize <= 0) {
                throw new IllegalArgumentException("Cache size must be greater than zero");
            }
            this.cacheSize = cacheSize;

            int hashTableCapacity = (int) Math.ceil(cacheSize / hashTableLoadFactor) + 1;
            this.delegate = new LinkedHashMap<K, V>(hashTableCapacity, hashTableLoadFactor, true) {
                private static final long serialVersionUID = 2016748957655976689L;

                @Override
                protected boolean removeEldestEntry(Map.Entry<K, V> eldest) {
                    return super.size() > LruCache.this.cacheSize;
                }
            };
        }
    }

    public static void main(String[] args) {
        LruCache lruCache = new LruCache(10);
        FSTConfiguration configuration = FSTConfiguration.createDefaultConfiguration();
        configuration.setShareReferences(false);
        byte[] bytes = configuration.asByteArray(lruCache);
        Object o = configuration.asObject(bytes);
    }
```

And the exception:

```
Exception in thread "main" java.lang.StackOverflowError
    at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:89)
    at java.lang.reflect.InvocationTargetException.<init>(InvocationTargetException.java:72)
    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.nustaq.serialization.FSTObjectOutput.writeObjectCompatibleRecursive(FSTObjectOutput.java:546)
    at org.nustaq.serialization.FSTObjectOutput.writeObjectCompatibleRecursive(FSTObjectOutput.java:542)
    at org.nustaq.serialization.FSTObjectOutput.writeObjectCompatibleRecursive(FSTObjectOutput.java:542)
    at org.nustaq.serialization.FSTObjectOutput.writeObjectCompatible(FSTObjectOutput.java:534)
    at org.nustaq.serialization.FSTObjectOutput.writeObjectWithContext(FSTObjectOutput.java:441)

```

It would be fine if we set the share reference to true, but we still hope we can set it to false since we have met some other performance issues when set it to true.

**Comment by RuedigerMoeller** [comment]
If you set share references to false, you cannot serialize cyclic linked data structures. This mode is usable for specially designed "message classes" comparable to what one would use with protobuf or similar flat binary encodings. Shared references=true requires to to check each Object if it has been serialized and thereby implicitely handles cyclic structures. 

Adding cycle detection to non-shared mode would basically destroy any performance advantage.

LinkedHashMap should be handled by a custom serializer already (at least with fst 2.4x), so it seems you are putting some Class falling back to default serialization ("writeObjectCompatible") into the cache.
You need to identify the problematic class and add a custom serializer avoiding the cyclic reference.

Another option would be to make use of the @Flat annotation. Using this one could turn off cycle detection/shared references on a by-class / by-reference level.

Running into performance issues when sharing references is frequently caused by poor stock JDK readObject/writeObject implementations, so probably your best bet would be to turn on reference sharing and figure out which classes are falling back to "writeObjectCompatible". FST speeds up generic Object serialization the most, in case it falls back to JDK-emulation its still faster, however the gain is not that big anymore. Frequently its only one or two specific classes slowing down, so register a custom serializer for those.

**Comment by lcy2008a** [comment]
Ok. I see. I tried the LinkedHashMap and it will use FstMapSerializer. From the source code the FST finds the serializer just by class name, so if I used subclass for LinkedHashMap, it also reports error. 

Could FST be changed to support subclass for such case? I mean can FST use method like isAssignableFrom to get serializer and record the class type in some where?

**Comment by RuedigerMoeller** [comment]
this can be adjusted when registering the serializer (boolean flag). However take care, for many cases serializers do not work automatically for all subclasses.

**Comment by mibac138** [comment]
Offtopic;
At first I thought you mean stackoverflow.com
