### ISSUE TITLE
Comparison to Capnproto and javolution Struct ?

### ISSUE THREAD

**Issue by kk00ss** [RuedigerMoeller/fast-serialization#122]
Hello, I'm interested in performance comparison and general overview of differences with similar projects ?

https://github.com/sandstorm-io/capnproto
http://javolution.org/apidocs/index.html?javolution/io/Struct.html

**Comment by kk00ss** [comment]
So far I see that Javolution Struct requires you to use their own types like Unsigned16 , and Capnproto requires schema defined upfront. So fast-serialization look easier to integrate into existing project.

**Comment by RuedigerMoeller** [comment]
high performance serialization is more convenient compared to "message definition based" encodings. In addition there is no need to transform application data objects into messages and vice versa (most benchmark don't include those extra steps). Most wire formats don't support inter linked object graphs.

On the downside one has to be careful regarding binary compatibility when changing serialized classes. However this is a matter of organization + discipline.

structs are a rather tricky workaround to allow for huge datasets off-heap. FST uses a bytecode manipulation approach to transform on heap "template" classes to flat off-heap-memory layouts. Its kind of a "crazy" workaround to overcome the JVM memory handling and one really has to understand in depth what's going on.

However if you are at the forefront of what's rechnically possible, there is no real alternative. Example where structs are used in real world projects:

* ultra fast messaging. Similar to C there is no encoding / decoding. You can take the underlying bytes of a struct, send it over the wire and for decoding just set a "struct pointer" to the base of the byte array. The only way to actually saturate a 10GB network with java messaging currently (see e.g. fast-cast)
* make use of large machine memory. In a NLP/machine learning appplication, fst-structs are used to deal with N-Gram-Tree's of sizes beyond 32GB. Due to the flat continuous memory layout, I can search those lineary within 2-3 seconds. Same data "on-heap" would be completely impractical (>150GB, endless GC's, slow operation due to cache-unfriendly heap structure). As NLP is mostly a matter of mass, these kind of technical improvements gives a substantial advantage compared to naive implementations of similar algorithm implementations running on the JVM.
