### ISSUE TITLE
low performance of serialization

### ISSUE THREAD

**Issue by MikeHerasimov** [RuedigerMoeller/fast-serialization#125]
Hi!
I tried fast-serialization library with example from here [http://java-is-the-new-c.blogspot.com/2013/10/still-using-externalizable-to-get.html](url) 

I serialized single instance of BlogBench, using this method 
`public void write(OutputStream stream) throws IOException{
        FSTObjectOutput out = new FSTObjectOutput(stream);
        out.writeObject(this);
        out.close();
    }`
I putted instance of FileOutputStream as a param.
And performance was almost the same as with usage of standard Serializable and ObjectOutputStream.
So what I'm doing wrong?
Also is there some docs or tutorials, which describes usage of fast-serialization library?

**Comment by RuedigerMoeller** [comment]
you are measuring the cost of opening, creating and closing a FileOutputStream. Serialization in your sample will be less than 1% of runtime. Also ensure proper JIT warmup when benchmarking.

**Comment by MikeHerasimov** [comment]
ok, I'm not argue with you about this,  but if I perform serialization of int array with 1 000 000 elements standard approach performance are much better - nearly 130 ms vs 200

**Comment by mafagafogigante** [comment]
There are literally dozens (if not hundreds) of projects using this library, and not to serialize fake data, but real-world related object collections. Developers are not doing it because of marketing or because they like doing it in a slower way.

It is absurdly naive to assume that your benchmarkings are correct and that you are right after just looking at the numbers. Not to mention that the author himself just wrote what you are doing wrong.

Closing as misleading and unhelpful.

**Comment by RuedigerMoeller** [comment]
for a pure large int array this might be true as JDK uses some private native code for this special case. just check real world data, the difference is factors 2 to >5 usually.

**Comment by RuedigerMoeller** [comment]
if you use unsafe configuration FST makes use of native code (Unsafe class). See also #61
