### ISSUE TITLE
null objects serialization 

### ISSUE THREAD

**Issue by aferraria** [RuedigerMoeller/fast-serialization#182]
in some cases i am obtain not null value from a field that i was checked as null

for example, in this line in FSTObjectOutput class
Object subObject = subInfo.getObjectValue(toWrite);
I obtain a not null value from a field checked as null in toWrite object

for me, is strange. Also seems to occur randomly
Also, if I use an eclipse debugger and re-run the method, I get a null value!

I use jvm 1.8.0_121

Any Idea?

thank you very much!

**Comment by RuedigerMoeller** [comment]
which encoding do you use ? (json or binary)

**Comment by aferraria** [comment]
binary

**Comment by RuedigerMoeller** [comment]
as fst is in production in many places I doubt there is a fundamental flaw like that. There must be some special condition.

Some questions:
* do you use createDefaultConfiguration() [not createUnsafeBinary]
* are those fields "transient" with default values like `transient String x = "Hello"` ?
* what "non-null" values do you see (what object is there instead of expected null value)
* is it a multithreaded app, is the error reproducable if you single-thread/synchronize or use a thread-locl fstconfiguration ?

thanks for supporting fst :)

**Comment by aferraria** [comment]
1)	i use a default configuration
2)	those fields ar no tansient 
3)	i use fst as the wicket serialization tool.  the not null values are the values that i set as null just before start the serialziation process. Form example: model.a = value->model.a=null->serialize model->model.a=value in serialization.
4)	I reproduce the case in a single thread environment

**Comment by RuedigerMoeller** [comment]
reagarding 3., this is technically impossible, how should fst sniff out previously set values, I mean this information (previous value of a field) is not present inside the JVM if the order of action is as you describe.

**Comment by debop** [comment]
Use ValueWrapper having original object

**Comment by RuedigerMoeller** [comment]
closing as no reproducable testcase provided. Description is not logical as old objects magical reappear.
