### ISSUE TITLE
Different representation of the same object when serialization is repeated

### ISSUE THREAD

**Issue by Pryanic** [RuedigerMoeller/fast-serialization#206]
After the first serialization in the json string,  FST adds a space at the beginning of the line.
![selection_495](https://user-images.githubusercontent.com/13783593/28716405-c25ba5f8-73a5-11e7-9136-5305aae3b5ef.png)
![selection_496](https://user-images.githubusercontent.com/13783593/28716404-c25705a2-73a5-11e7-9932-56577c44f263.png)

**Comment by aminka-16** [comment]
+1, we've also faced the same problem with FST

**Comment by vgladush** [comment]
+1 so I had the same problem

**Comment by RuedigerMoeller** [comment]
ok,  that's strange

**Comment by RuedigerMoeller** [comment]
btw, sending a cut and paste'able test case is strongly preferred over gifs ;)

**Comment by RuedigerMoeller** [comment]
caused by missing reset of Jackson Stream generator. Unfortunately the reset method is protected and construction of Stream generator is not overrideable. Now create a new generator with each json serialization (no caching) as it seems Jackson factor does reuse behind the scenes anyway.

Fixed with 2.52
