### ISSUE TITLE
versions compatibility

### ISSUE THREAD

**Issue by myshzzx** [RuedigerMoeller/fast-serialization#220]
fst is so fast and efficiency , but still hard to use in rpc serialization or data persistence scene like redis, because it's not compatible backward or forward (forget @Version, it's too complex to manage versions, in hundreds of fields and classes). 
It's acceptable to trade 30% speed or more for version compatibility, without this, fst can be used only in short term temporary persistence.
default value is not a big problem, because it's the thing that code logic to care about, not fst.

**Comment by RuedigerMoeller** [comment]
kind of agree. however the perf tradeoff is much worse than 30%, as actually one needs to use kind of key-value + type tagging for each field. currently fst writes field values straigtht without any tagging and reads them straight forward.

I theoretically could implement some basic incompatibility detection using serializedVersionId, however I never found this one that useful.

think about it: one needs to somehow have a unique id for each field of a class, you'll also need to denote the field's type in order to be able to handle versioning gracefully. This will be extremely expensive and slow down fst by a factor of 3 or more (I squeezed on every nano, so even small changes can have big performance impact).

One will end up with a json-alike performance, so why not just could use the json encoder then ...

Another approach I thought of is to generate class-layout metadata, which then can be sent once e.g. upon connect. This way fst could compare meta-data of different versions, but this requires ahead of time knowledge of classes being serialized and kind of a connection protocol: I assume nobody will use it in practice.

Actually there is no protocol on the market which can handle versioning "magically": they either work with data tagging (json => but fails on field type changes) or manual declaration of "extension data".

**Comment by myshzzx** [comment]
json encode field name in each instance, if you serialize a big list, it's a waste of space.
Extreme performance is not the only factor we consider about. If one can have json performance ( fastjson is fast than jdk) and less space (less than json, faster in network transfer) and more easy to use (don't need to maintain IDL like thrift or protobuf), it will win the market.

**Comment by RuedigerMoeller** [comment]
I have experimented with something along this with "MinBin" [~binary json] encoding (there is a unsupported fstconfiguration using this). However this does not help magically in handling version conflicts. 
Only at detail level you'll recognize "magic" version conflict handling is a pipe dream. That's why no simple solution exists after 50 years of programming history.

Even if one adds a block of layout information to the start of each serialized object (to avoid repeating), there is still no simple solution on how to apply an old version of an object-graph to a new one.

Anyway I agree it would be quite helpful to optionally enable at least field additions / removement. I might implement this once I am involved in commercial work requiring this, I won't implement this in my spare time.

"it will win the market."
there is no market. Open Source (especially foundation libraries like fst) means a "lot of work for free". With ~22.000 maven downloads per month (~12000 unique IP's) fast-ser (accumulated time invested: ~0,5 man year ) has not brought me any significant advantage neither financially nor in "job-interviews" (many agencies see heavy open source contribution as an indication for 'lack of employment').
