### ISSUE TITLE
Skip serialization of transient fields

### ISSUE THREAD

**Issue by Elgeor** [RuedigerMoeller/fast-serialization#58]
Hi Mr. Ruediger,

I have question more than issue. I have object which has reference to other quite big other objects. I don't want to serialize this objects so I change this references to transient (eg.: private transient MyProcessor myProcessor;) I also annotate MyProcessor interface with org.nustaq.serialization.annotations.Transient annotation but it still ends up with stack overflow because of recurrent reference. Can you please give me some advice how to solve this issue?

**Comment by RuedigerMoeller** [comment]
I don't know of issues regarding processing of 'transient' fields (there where issues in very old 1.x releases though). You probably have other references to your huge objects (e.g. inside collections).
A recurrent reference should be detected, fst never serializes an object twice.
Ensure you don't have set the "unshared" option on the FSTConfiguration, because this would turn off recurrent reference detection. Remove the @Transient annotation as it should be sufficient to set fields to transient.
If you think FST is ignoring "transient", please try to file a reproducer.

You can set a break point to the writeObjectInternal method, so you are able to track back where the object reference is coming from ('referencee' usually contains the field referencing a serialized object).

A dirty workaround would be registration of an "empty" serializer for the class you want to avoid, this could ressolve to 'null' at deserialization time and has an empty write method on serialization time. However this is really dirty, I'd recommend to find the error either in your (or my :-) ) code.

**Comment by Elgeor** [comment]
Hi,

I find out, what was problem, unfortunately right after this post. Please close it. This was no issue at all. Thank you for your attention and quick answer.
