### ISSUE TITLE
Unnecessary getIdFromClazz lookup in FSTClazzNameRegistry.encodeClass

### ISSUE THREAD

**Issue by esemsch** [RuedigerMoeller/fast-serialization#76]
Hi, 

I've noticed one thing when serializing a rather big object graph.  In this method: https://github.com/RuedigerMoeller/fast-serialization/blob/master/src/main/java/org/nustaq/serialization/FSTClazzNameRegistry.java#L94 ```clInfo.setClzId(id);``` is never called for "my" classes because parent is not null.  

This means that every time a "my" class is serialized in https://github.com/RuedigerMoeller/fast-serialization/blob/master/src/main/java/org/nustaq/serialization/FSTClazzNameRegistry.java#L121 (which is millions of times), this method gets called ```getIdFromClazz(aClass);``` This method is expensive because it involves a map lookup operation.

What is the purpose of the null check in the ```addClassMapping``` method?  Is it really doing what it should be?  

Thanks and keep up the great work,

Eduard

**Comment by RuedigerMoeller** [comment]
hi,

1) there is a hierarchy of classname registry's. For system classes add in fstconfiguration, an id is added such that no fq classnames have to be written. (That's why `clInfo.setClzId(id);` is called only on the root registry). 

2) for user defined classes, registration is done on a per stream base such that a fq classname is only written once, after that an id is written. However this id has to be abandonned after the particular stream is closed. You can preregister user-level classes in order to avoid writing full qualified clnames.

3) null check in addClassMapping() needs to be there. The parameter is passed just in case the caller somehow already did a lookup. If not, classinfo must be looked up (and might be created at this point, lazy init)

5)  `getIdFromClazz(aClass);`. As said, full qualified classnames are only written once per stream, therefore this unification call needs be done (read side is symmetric such that class id's are generated in identical order as in write side). If this is ommitted, full qualified class names had to be written for any instance which would slow down much more than the hash lookup

regards,
rüdiger

**Comment by esemsch** [comment]
HI Rüdiger,

It makes perfect sense now.  My case is special in that I only serialize one big object graph and then exit the code.  I have done as you said and pre-registered my classes and it hasn't made much difference, and I can confirm the lookup is not being called.    

Thanks for your time, I am absolutely happy for you to close this issue,

Eduard
