### ISSUE TITLE
FSTStreamDecoder can clobber buffers

### ISSUE THREAD

**Issue by rdicroce** [RuedigerMoeller/fast-serialization#91]
This is a nasty bug that I just spent all day finding. FSTStreamDecoder#resetToCopyOf() improperly reuses the buffer that FSTInputStream already has. This creates a problem if you mix-and-match different FSTConfiguration#getObjectInput*() methods.

Test code:
```java
	public static void main(String[] args) throws Exception {
		FSTConfiguration config = FSTConfiguration.createDefaultConfiguration();
		FSTObjectOutput out = config.getObjectOutput();
		out.writeObject("foobar");
		byte[] savedBuffer = out.getCopyOfWrittenBuffer();
		byte[] reallySavedBuffer = Arrays.copyOf(savedBuffer, savedBuffer.length);
		out.resetForReUse();
		out.writeObject("blah");
		byte[] secondBuffer = out.getCopyOfWrittenBuffer();
		
		config.getObjectInput(savedBuffer);
		config.getObjectInputCopyFrom(secondBuffer, 0, secondBuffer.length);
		System.out.println(Arrays.equals(savedBuffer, reallySavedBuffer));
		System.out.println(Arrays.toString(savedBuffer));
		System.out.println(Arrays.toString(reallySavedBuffer));
	}
```

At the end of the method, one would expect that savedBuffer and reallySavedBuffer contain the same bytes, but they don't. The call to getObjectInput() sets FSTInputStream's buffer to savedBuffer, and then the call to getObjectInputCopyFrom() clobbers savedBuffer by copying secondBuffer on top of it.

There are many ways this could be fixed, but the simplest would be to allocate a new array in FSTStreamDecoder#resetToCopyOf() and copy to that instead of copying to the last buffer FSTObjectInput was looking at. I have not checked the other FSTDecoder implementations, but it is possible they have the same problem.

**Comment by RuedigerMoeller** [comment]
Thanks a lot for your efforts and bug report, I'll dive into details as soon I find time.

**Comment by RuedigerMoeller** [comment]
Hi, I think this is expected behaviour. When calling `config.getObjectInput(savedBuffer)` one hands over ownership of the buffer to the object input and it will reuse this buffer in case.

Issue with defensive copying is, that it has severe impact on throughput/performance (e.g. for high throughput messaging). This can easily lead to 100's of MB additional garbage per second.

So I prefer to have the caller be responsible to use `config.getObjectInputCopyFrom()` instead of `getObjectinput()` or manually copy the array before calling `getObjectInput(arr)`.

I agree this is not very intuitive, however you cannot be fast and completely safe at the same time. Defensive copying is one of the reasons stock IO in JDK performs bad.

I will add at least some warning JavaDoc :) + thanks again for reporting.
